# Generated by Django 3.2.16 on 2022-10-28 09:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Task name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Task description')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In Progress'), ('Checking', 'Checking'), ('Closed', 'Closed')], default='Open', max_length=100, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In progress', 'In Progress'), ('Checking', 'Checking'), ('Closed', 'Closed')], default='Open', max_length=100, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Project'),
        ),
    ]
